// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apbd_12.Data;

#nullable disable

namespace apbd_12.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250605212914_AddClientTripAndCountryTripSeeds")]
    partial class AddClientTripAndCountryTripSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apbd_12.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdClient");

                    b.ToTable("Client", (string)null);

                    b.HasData(
                        new
                        {
                            IdClient = 1001,
                            Email = "john@doe.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Pesel = "1265E789AD",
                            Telephone = "0888888888"
                        },
                        new
                        {
                            IdClient = 1002,
                            Email = "maryjane@yahoo.com",
                            FirstName = "Mary",
                            LastName = "Jane",
                            Pesel = "TR3434PO10",
                            Telephone = "0715931422"
                        },
                        new
                        {
                            IdClient = 1003,
                            Email = "jade79@gmail.com",
                            FirstName = "Jade",
                            LastName = "Aldemir",
                            Pesel = "EM7LP82112",
                            Telephone = "0553412210"
                        },
                        new
                        {
                            IdClient = 1004,
                            Email = "kcrane@yahoo.com",
                            FirstName = "Kyle",
                            LastName = "Crane",
                            Pesel = "10APOL300F",
                            Telephone = "0567002120"
                        });
                });

            modelBuilder.Entity("apbd_12.Models.ClientTrip", b =>
                {
                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdTrip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdClient", "IdTrip");

                    b.HasIndex("IdTrip");

                    b.ToTable("ClientTrip", (string)null);

                    b.HasData(
                        new
                        {
                            IdClient = 1001,
                            IdTrip = 1,
                            PaymentDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisteredAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdClient = 1003,
                            IdTrip = 2,
                            RegisteredAt = new DateTime(2015, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdClient = 1004,
                            IdTrip = 2,
                            PaymentDate = new DateTime(2015, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisteredAt = new DateTime(2015, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("apbd_12.Models.Country", b =>
                {
                    b.Property<int>("IdCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCountry"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdCountry");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            IdCountry = 1,
                            Name = "Canada"
                        },
                        new
                        {
                            IdCountry = 2,
                            Name = "Turkey"
                        },
                        new
                        {
                            IdCountry = 3,
                            Name = "Poland"
                        });
                });

            modelBuilder.Entity("apbd_12.Models.CountryTrip", b =>
                {
                    b.Property<int>("IdTrip")
                        .HasColumnType("int");

                    b.Property<int>("IdCountry")
                        .HasColumnType("int");

                    b.HasKey("IdTrip", "IdCountry");

                    b.HasIndex("IdCountry");

                    b.ToTable("CountryTrip", (string)null);

                    b.HasData(
                        new
                        {
                            IdTrip = 1,
                            IdCountry = 1
                        },
                        new
                        {
                            IdTrip = 2,
                            IdCountry = 2
                        },
                        new
                        {
                            IdTrip = 3,
                            IdCountry = 3
                        });
                });

            modelBuilder.Entity("apbd_12.Models.Trip", b =>
                {
                    b.Property<int>("IdTrip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrip"));

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MaxPeople")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdTrip");

                    b.ToTable("Trip", (string)null);

                    b.HasData(
                        new
                        {
                            IdTrip = 1,
                            DateFrom = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A quick little tour to Canada.",
                            MaxPeople = 10,
                            Name = "Niagara Falls Excursion"
                        },
                        new
                        {
                            IdTrip = 2,
                            DateFrom = new DateTime(2015, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2015, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A mission to retrieve a file capable to save humanity.",
                            MaxPeople = 5,
                            Name = "Harran Expedition"
                        },
                        new
                        {
                            IdTrip = 3,
                            DateFrom = new DateTime(2015, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2015, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A cozy vacation at breathtaking range of Carpathians mountains.",
                            MaxPeople = 8,
                            Name = "Zakopane Vacation"
                        });
                });

            modelBuilder.Entity("apbd_12.Models.ClientTrip", b =>
                {
                    b.HasOne("apbd_12.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbd_12.Models.Trip", "Trip")
                        .WithMany("ClientTrips")
                        .HasForeignKey("IdTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("apbd_12.Models.CountryTrip", b =>
                {
                    b.HasOne("apbd_12.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbd_12.Models.Trip", "Trip")
                        .WithMany("CountryTrips")
                        .HasForeignKey("IdTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("apbd_12.Models.Trip", b =>
                {
                    b.Navigation("ClientTrips");

                    b.Navigation("CountryTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
